trigger:
- main

pool:
  vmImage: ubuntu-latest

stages: 
  - stage: Build
    jobs: 
     - job: job1
       steps: 
       - script: echo job 1 hello hello
       displayName: 'Run my script'
     - job: job2
       steps: 
       - script: echo job 2 hello hello 
       displayName: 'Run my script 2'

  - stage: Test
    jobs: 
     - job: job1
       steps: 
       - script: echo job 1 hello hello
       displayName: 'Run my script'
     - job: job2
       steps: 
       - script: echo job 2 hello hello 
       displayName: 'Run my script 2'