trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: job1
        displayName: Run my script
        steps:
          - script: echo job 1 hello hello

      - job: job2
        displayName: Run my script 2
        steps:
          - script: echo job 2 hello hello

  - stage: Test
    jobs:
      - job: job1
        displayName: Run my script
        steps:
          - script: echo job 1 hello hello

      - job: job2
        displayName: Run my script 2
        steps:
          - script: echo job 2 hello hello

  - stage: Test2
    dependsOn:
      - Test
    jobs:
      - job: job1
        displayName: Run my script
        steps:
          - script: echo job 1 hello hello

      - job: job2
        displayName: Run my script 2
        steps:
          - script: echo job 2 hello hello
